sudo: false
language: node_js
node_js:
  - '8'
services:
  - mongodb
before_script:
  - mongo --port 27017 --eval 'db.createCollection("Country");db.Country.insert({CNname:"中国",ENname:"CHINA",Shortening:"CN",contrynum:156,countryTelnum:86});db.Country.find();'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
