sudo: false
language: node_js
node_js:
  - '8'
services:
  - mongodb
install:
  - npm i npminstall && npminstall
script:
  - node crawler_country.js
  - npm run ci
after_script:
  - npminstall codecov && codecov
