sudo: false
language: node_js
node_js:
  - '8'
services:
  - mongodb
before_script:
  - mongo --port 27017 --eval 'db.createCollection("country");'
  - mongo --port 27017 --eval 'db.country.insert({CNname:"中国",ENname:"CHINA",Shortening:"CN",contryNum:156,countryTelnum:86});'
  - mongo --port 27017 --eval 'db.country.insert({CNname:"日本",ENname:"JAPAN",Shortening:"JP",contryNum:392,countryTelnum:81});'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
