sudo: false
language: node_js
node_js:
  - '6'
  - '8'
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createCountry({CNname:"中国",ENname:"CHINA",Shortening:"CN",contrynum:156,countryTelnum:86});'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
